[package]
name = "c4_1_4_variables_and_data_move"
version = "0.1.0"
authors = ["Ian Price <ianprice943@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
